name = "komodo-alert-to-telegram"
main = "app.js"
compatibility_date = "2023-10-30"

[vars]
# For local development only
# API_SECRET_KEY = "your_api_secret_key_for_development"
# TELEGRAM_BOT_TOKEN = "your_bot_token_for_development"
# TELEGRAM_CHAT_ID = "your_chat_id_for_development"
# KOMODO_URL = "https://your-komodo-server/

# Your environment variables go here

# Enable log collection
[triggers]
crons = []

# Configure logging
[observability.logs]
enabled = true