name = "komodo-alert-to-telegram"
main = "app.js"
compatibility_date = "2023-10-30"
workers_dev = true

[build]
command = ""

[vars]
# For local development only
# API_SECRET_KEY = "your_api_secret_key_for_development"
# TELEGRAM_BOT_TOKEN = "your_bot_token_for_development"
# TELEGRAM_CHAT_ID = "your_chat_id_for_development"
# KOMODO_URL = "https://your-komodo-server/"
# DEBOUNCE_SECONDS = "60"

# Your environment variables go here

# Durable Object bindings
[durable_objects]
bindings = [
  { name = "ALERT_DEBOUNCER", class_name = "AlertDebouncer" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["AlertDebouncer"]

# Configure logging
[observability.logs]
enabled = true